# Generated by Django 3.2.9 on 2021-12-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
