# Generated by Django 3.2.9 on 2021-12-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish_fb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='username',
            field=models.TextField(default=0.0009896091044037606),
            preserve_default=False,
        ),
    ]
